### ISSUE TITLE
Delete button not working

### ISSUE THREAD

**Issue by eriksdev1** [jmakila/SavePinned#3]
Extension version: 1.0.5
Browser: Vivaldi 2.1.1337.47, win8.1 x64

I can't delete a tab set when pressing the delete button, any hints what might be happening ?

Thanks, this one is a great extension

**Comment by jmakila** [comment]
Hi, this has to do with the Vivaldi browser. When you delete a set it's
supposed to show a confirmation popup. I think Vivaldi might be suppressing
this popup somehow and that's why sets can't be deleted. I don't know the
browser well enough to give any advice on how to remedy this.
Unfortunately, there is a high probability that this extensions isn't fully
supported by Vivaldi.

**Comment by oraant** [comment]
@eriksdev1 Have you shared your plugin in the chrome store? Really want to try..

**Comment by mattyg** [comment]
This issue has been reported by several users in the Chrome Web Store.

We may want to consider refactoring the `alert` confirmation to an alternative in-page modal dialog, to avoid interference by popup blockers.
